---
# tasks file for cisco_banner

- name: configure_cisco.ios.ios | Set login banner.
  cisco.ios.ios_banner:
    banner: login
    text: "{{ lookup('file', 'banner.cfg') }}"
    state: present
  when: ansible_facts.date_time.month != '12'
  notify: Save ios.

- name: configure_cisco.ios.ios | Set xmas-banner.
  cisco.ios.ios_banner:
    banner: login
    text: "{{ lookup('file', 'xmas_banner.cfg') }}"
    state: present
  when: ansible_facts.date_time.month == '12'
  notify: Save ios.
