---
# tasks file for network_banner

- name: Gather facts from localhost
  ansible.builtin.setup:
  delegate_to: localhost
  run_once: true

- name: Include tasks
  ansible.builtin.include_tasks:
    file: "{{ ansible_network_os }}.yml"
